version: '3'
services:
  node:
      image: 'node:10-alpine'
      volumes:
        - './:/home/node/app'
      working_dir: '/home/node/app'
      depends_on:
        - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo/SampleCollections:/usr/local/sampleCollections
    working_dir: /usr/local/sampleCollections
