POST http://localhost:3000/movies
Content-Type: application/json

{
  "Title": "Bad Boys 3"
}

###
GET http://localhost:3000/movies

###
GET http://localhost:3000/movies/ACADEMY DINOSAUR

###
DELETE http://localhost:3000/movies/ACADEMY DINOSAUR
###
PUT http://localhost:3000/movies/Bad Boys 3
Content-Type: application/json

{
  "Title": "ACADEMY DINOSAUR"
}

###

GET http://localhost:3000/crypto/

###

POST http://localhost:4000/crypto/updateCMCData
Content-Type: application/json

{
}

###

GET http://localhost:4000/crypto/updateCGData
Content-Type: application/json

{
}

###

GET https://api.coingecko.com/api/v3/coins/markets?vs_currency=eur&order=market_cap_desc&per_page=100&page=1&sparkline=false
